---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None #this is called headless service
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
    
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      #has to match .spec.template.metadata.labels
      component: mysql
      project: expense
      tier: db
  serviceName: "mysql-headless" #provide headless server
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        #has to match .spec.selector.matchLabels
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: lingadevops/mysql:v1.1
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  #PVC declaration, it is mandatory, each pod requires its own volume
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs-sc"
      resources:
        requests:
          storage: 1G

#We are using ebc dynamic provision, it requires storage class.

          


















# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: mysql
#   namespace: expense
#   # these labels are deployment related labels
#   labels:
#     component: mysql
#     project: expense
#     tier: db
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       component: mysql
#       project: expense
#       tier: db
#   # pod definition
#   template:
#     metadata:
#       labels:
#         component: mysql
#         project: expense
#         tier: db
#     spec:
#       containers:
#       - name: mysql
#         image: lingadevops/mysql:v1.0
#         readinessProbe:
#           tcpSocket:
#             port: 3306
#           initialDelaySeconds: 10
#           periodSeconds: 5
#         livenessProbe:
#           tcpSocket:
#             port: 3306
#           initialDelaySeconds: 10
#           periodSeconds: 5


           